# Generated by Django 4.1.4 on 2023-01-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="holiday",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
